### ISSUE TITLE
rake assets:precompile on heroku failing. Can't find module './implementation'

### ISSUE THREAD

**Issue by Jshyu523** [browserify-rails/browserify-rails#164]
Hi all,

I can't figure out what exactly is this problem when trying to deploy to Heroku. Below is the error message I'm getting:

```
remote:        rake aborted!
remote:        BrowserifyRails::BrowserifyError: Error while running `/tmp/build_0e7578747ae20f125e6ec8ee39fb05b5/node_modules/.bin/browserify -t reactify --extension=".jsx" --list -o "/tmp/build_0e7578747ae20f125e6ec8ee39fb05b5/tmp/cache/browserify-rails/output20160424-1178-tu924v" -`:
remote:        module.js:341
remote:        throw err;
remote:        ^
remote:        Error: Cannot find module './implementation'
remote:        at Function.Module._resolveFilename (module.js:339:15)
remote:        at Function.Module._load (module.js:290:25)
remote:        at Module.require (module.js:367:17)
remote:        at require (internal/module.js:16:19)
remote:        at Object.<anonymous> (/tmp/build_0e7578747ae20f125e6ec8ee39fb05b5/node_modules/browserify/node_modules/has/node_modules/function-bind/index.js:1:84)
remote:        at Module._compile (module.js:413:34)
remote:        at Object.Module._extensions..js (module.js:422:10)
remote:        at Module.load (module.js:357:32)
remote:        at Function.Module._load (module.js:314:12)
remote:        at Module.require (module.js:367:17)
```

Here is my application.rb:
```
module Test
  class Application < Rails::Application
    config.active_record.raise_in_transactional_callbacks = true
    config.browserify_rails.commandline_options = "-t reactify --extension=\".jsx\""
    config.browserify_rails.node_env = "production"
    config.react.addons = true
  end
end
```

Here is my package.json:
```
{
  "name": "test",
  "dependencies": {
    "browserify": "^12.0.1",
    "browserify-incremental": "^3.0.1",
    "chart.js": "^1.0.2",
    "classnames": "^2.2.1",
    "flux": "^2.1.1",
    "object-assign": "^4.0.1",
    "react": "^0.14.7",
    "react-chartjs": "^0.7.3",
    "react-dom": "^0.14.7",
    "react-tooltip": "^1.1.2",
    "reactify": "^1.1.0"
  },
  "license": "MIT",
  "engines": {
    "node": ">= 0.10"
  }
}
```

rake assets:precompile RAILS_ENV=production works just fine. I've also configured the buildpacks to have nodejs first, then ruby.

Anyone ever run into this issue? Any tips will help. Thanks

**Comment by cymen** [comment]
Do you have a module pulled in with something like `var implementation  require('./implemenation');` -- if so, can you show that line. And do you have any configuration at all in any of the other environmental files in config? Like maybe adding an asset path in the development environment?

It is odd that it works fine with production locally so it suggests it's not the configuration but wanted to ask.

**Comment by Jshyu523** [comment]
Hi @cymen thanks for your reply.

There seems to be a file called implementation.js located here: /node_modules/browserify/node_modules/has/node_modules/function-bind/implementation.js

and a index.js file located in the same folder with the following code:

```
var implementation = require('./implementation');

module.exports = Function.prototype.bind || implementation;
```

The following is my development.rb:

```
Rails.application.configure do
  config.cache_classes = false
  config.eager_load = false
  config.consider_all_requests_local       = true
  config.action_controller.perform_caching = false
  config.action_mailer.raise_delivery_errors = false
  config.active_support.deprecation = :log
  config.active_record.migration_error = :page_load
  config.assets.debug = true
  config.assets.digest = true
  config.assets.raise_runtime_errors = true
  config.assets.raise_production_errors = true
  config.react.variant = :development
end
```

The following is my production.rb:
```
Rails.application.configure do
  config.cache_classes = true
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = true

  # Disable serving static files from the `/public` folder by default since
  # Apache or NGINX already handles this.
  config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?
  config.assets.js_compressor = :uglifier
  config.assets.compile = false
  config.assets.digest = true
  config.log_level = :debug
  config.i18n.fallbacks = true
  config.active_support.deprecation = :notify
  config.log_formatter = ::Logger::Formatter.new
  config.active_record.dump_schema_after_migration = false
  config.react.variant = :production
end
```

Again, thanks for the reply and for all of your help

**Comment by Jshyu523** [comment]
Some additional info about the error message:

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        I, [2016-04-24T18:54:47.417643 #1180]  INFO -- : Writing /tmp/build_54db60ca85aa0c718fcbc96133781086/public/assets/home-library-c28e9a8fa5bb96c2587feedfcfaf311f09932aed6a0a3478d02c1da05be5b84a.jpg
remote:        I, [2016-04-24T18:54:47.421063 #1180]  INFO -- : Writing /tmp/build_54db60ca85aa0c718fcbc96133781086/public/assets/icon/missing-9115096dfabfa2e40861fdde4cbf3f58ee4344fdb41e373ee2e2366572ed716a.png
remote:        I, [2016-04-24T18:54:47.423288 #1180]  INFO -- : Writing /tmp/build_54db60ca85aa0c718fcbc96133781086/public/assets/thumb/missing-606f4f0d5b9cde17df19375e3509a8e515e846ef7ca1e68252ffb5a08fa8bcfb.png
remote:        Browserify: /tmp/build_54db60ca85aa0c718fcbc96133781086/node_modules/.bin/browserify -t reactify --extension=".jsx" --list -o "/tmp/build_54db60ca85aa0c718fcbc96133781086/tmp/cache/browserify-rails/output20160424-1180-1xktrwq" -
remote:        rake aborted!
remote:        BrowserifyRails::BrowserifyError: Error while running `/tmp/build_54db60ca85aa0c718fcbc96133781086/node_modules/.bin/browserify -t reactify --extension=".jsx" --list -o "/tmp/build_54db60ca85aa0c718fcbc96133781086/tmp/cache/browserify-rails/output20160424-1180-1xktrwq" -`:
remote:        module.js:341
remote:        throw err;
remote:        ^
remote:        Error: Cannot find module './implementation'
remote:        at Function.Module._resolveFilename (module.js:339:15)
remote:        at Function.Module._load (module.js:290:25)
remote:        at Module.require (module.js:367:17)
remote:        at require (internal/module.js:16:19)
remote:        at Object.<anonymous> (/tmp/build_54db60ca85aa0c718fcbc96133781086/node_modules/browserify/node_modules/has/node_modules/function-bind/index.js:1:84)
remote:        at Module._compile (module.js:413:34)
remote:        at Object.Module._extensions..js (module.js:422:10)
remote:        at Module.load (module.js:357:32)
remote:        at Function.Module._load (module.js:314:12)
remote:        at Module.require (module.js:367:17)
```

Seems like the first js file to get precompiled fails. Is there something wrong with the way I've written the command line options for browserify?

**Comment by Jshyu523** [comment]
I noticed I had some changes that weren't committed. Once I pushed those changes things started working as expected
