### ISSUE TITLE
required browserify 'cache' opt not set

### ISSUE THREAD

**Issue by joncursi** [browserify-rails/browserify-rails#169]
Hi,

I have npm installed `browserify` and `browserify-incremental` but I am getting the below error when I boot up rails:

```
Error while running `/Users/jcursi/Sites/proexam/scoring/node_modules/.bin/browserifyinc -d -t [ babelify --presets [ es2015 react stage-0 ] --plugins [ syntax-async-functions transform-regenerator ] ] --list --cachefile=/Users/jcursi/Sites/proexam/scoring/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/Users/jcursi/Sites/proexam/scoring/tmp/cache/browserify-rails/output20160719-31777-f6aru7" -`:

/Users/jcursi/Sites/proexam/scoring/node_modules/browserify-cache-api/lib/BrowserifyCache.js:19
  assert(b._options.cache, "required browserify 'cache' opt not set");
                   ^

TypeError: Cannot read property 'cache' of undefined
    at BrowserifyCache (/Users/jcursi/Sites/proexam/scoring/node_modules/browserify-cache-api/lib/BrowserifyCache.js:19:20)
    at browserifyIncremental (/Users/jcursi/Sites/proexam/scoring/node_modules/browserify-incremental/index.js:30:3)
    at run (/Users/jcursi/Sites/proexam/scoring/node_modules/browserify-incremental/bin/cmd.js:18:7)
    at Object.<anonymous> (/Users/jcursi/Sites/proexam/scoring/node_modules/browserify-incremental/bin/cmd.js:87:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```

Any ideas on how to set this `cache` option for browserify? Thanks!

**Comment by joncursi** [comment]
Can anyone point me in the right direction on this one?

**Comment by cymen** [comment]
Can you share the version of browserify and browserify-incremental that you're using (or the depedencies section of your package.json)?

**Comment by cymen** [comment]
Also if you take browserify-incremental out of the picture by setting:

`config.browserify_rails.use_browserifyinc = false`

Does it work (may be very slow)?

**Comment by joncursi** [comment]
Thanks for your response! When I add the line above to take browserify-incremental out of the picture, I get a different failure on the command line options:

```
Error while running `/Users/jcursi/Sites/proexam/scoring/node_modules/.bin/browserify -t [ babelify --presets [ es2015 react ] ] --list -o "/Users/jcursi/Sites/proexam/scoring/tmp/cache/browserify-rails/output20160725-26297-1e5m956" -`:

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received Socket {
  connecting: false,
  _hadError: false,
  _handle: 
   Pipe {
     bytesRead: 0,
     _externalStream: {},
     fd: 0,
     writeQueueSize: 0,
     owner: [Circular],
     onread: [Function: onread],
     reading: false },
  _parent: null,
  _host: null,
  _readableState: 
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: [],
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: false,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events: 
   { end: { [Function: g] listener: [Function: onend] },
     finish: [Function: onSocketFinish],
     _socketEnd: [Function: onSocketEnd],
     pause: [Function] },
  _eventsCount: 4,
  _maxListeners: undefined,
  _writableState: 
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     needDrain: false,
     ending: false,
     ended: true,
     finished: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: CorkedRequest { next: null, entry: null, finish: [Function] } },
  writable: false,
  allowHalfOpen: false,
  destroyed: false,
  _bytesDispatched: 0,
  _sockname: null,
  _writev: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  fd: 0 }
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at Browserify.deps (/Users/jcursi/Sites/proexam/scoring/node_modules/browserify/index.js:446:24)
    at Object.<anonymous> (/Users/jcursi/Sites/proexam/scoring/node_modules/browserify/bin/cmd.js:45:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```

Here is my package.json:

```
  "dependencies": {
    "babel-polyfill": "^6.9.1",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.1",
    "babelify": "^7.3.0",
    "browserify": "^4.1.11",
    "browserify-incremental": "^3.1.1",
    "react": "^15.2.1",
    "react-dom": "^15.2.1",
  },
```

I'm on rails 4.2.2

**Comment by joncursi** [comment]
Update:

Downgrading `browserify` and `browserify-incremental` to the following versions results in no errors:

```
    "browserify": "~10.2.4",
    "browserify-incremental": "^3.0.1",
```

Does anyone else have issues with the latest releases of these packages?

**Comment by gauravtiwari** [comment]
@joncursi Works with latest versions of both - browserify and incremental.

```json
    "browserify": "^10.2.6",
    "browserify-incremental": "^3.1.1",
```

repo here: https://github.com/gauravtiwari/browserify_on_rails

**Comment by cymen** [comment]
@gauravtiwari Would you mind if the browserify-rails README linked to your example repo? It seems like a good idea to have a working one with ES6, etc.

**Comment by gauravtiwari** [comment]
@cymen Sure, no problem. Do you want me to make a PR?

**Comment by cymen** [comment]
@gauravtiwari Sure!

**Comment by PikachuEXE** [comment]
Is the PR made?
Can this issue be closed?

**Comment by gauravtiwari** [comment]
@cymen Please close this issue. 

@PikachuEXE Yes.
