### ISSUE TITLE
Problem with transpilation of Javascript inside an Engine

### ISSUE THREAD

**Issue by lortega** [browserify-rails/browserify-rails#194]
I'm having an Issue while trying to load javascript from inside engines.

I have an example of my problem here: https://github.com/lortega/browserifyengineproblem

The thing is everything works fine until I add the line:

```
config.browserify_rails.commandline_options = "-t babelify"
```
in the `application.rb` of the Rails app mounting an Engine.

When I do that, I always get the following error:

```
Showing /Users/someuser/Workspace/Sandbox/browserifyengineproblem/test/dummy/app/views/layouts/application.html.erb where line #5 raised:

Error while running `/Users/someuser/Workspace/Sandbox/browserifyengineproblem/test/dummy/node_modules/.bin/browserifyinc -t babelify --list --cachefile=/Users/someuser/Workspace/Sandbox/browserifyengineproblem/test/dummy/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/Users/someuser/Workspace/Sandbox/browserifyengineproblem/test/dummy/tmp/cache/browserify-rails/output20170302-63655-1veq164" -`:

Error: Cannot find module 'babelify' from '/Users/someuser/Workspace/Sandbox/browserifyengineproblem/app/assets/javascripts/browserifyengineproblem'
    at /Users/someuser/Workspace/Sandbox/browserifyengineproblem/test/dummy/node_modules/resolve/lib/async.js:46:31
    at processDirs (/Users/someuser/Workspace/Sandbox/browserifyengineproblem/test/dummy/node_modules/resolve/lib/async.js:177:39)
    at ondir (/Users/someuser/Workspace/Sandbox/browserifyengineproblem/test/dummy/node_modules/resolve/lib/async.js:192:13)
    at load (/Users/someuser/Workspace/Sandbox/browserifyengineproblem/test/dummy/node_modules/resolve/lib/async.js:77:43)
    at onex (/Users/someuser/Workspace/Sandbox/browserifyengineproblem/test/dummy/node_modules/resolve/lib/async.js:100:31)
    at /Users/someuser/Workspace/Sandbox/browserifyengineproblem/test/dummy/node_modules/resolve/lib/async.js:23:47
    at FSReqWrap.oncomplete (fs.js:114:15)
```

**Comment by jcode** [comment]
me too

**Comment by hew** [comment]
@lortega 

`npm i --save-dev babelify`
