### ISSUE TITLE
not compiling on production after update to browserify 14.3.0

### ISSUE THREAD

**Issue by jefree** [browserify-rails/browserify-rails#202]
I have update the browser package version to 14.3.0 and it seems to not be compiling the files correctly, on `rake assets:precompile` everything looks fine, no errors, but after launch the app and go to the page i'm using some JS i'm getting `ReferenceError: MyComponent is not defined`, but if i come back to previous version (13.3.0), and precompile, everything works fine. 

It is just failing at production mode, in development it works as expected.

I've tried to look for the Component declaration within the compiled files and it doesn't appears anywhere, but in the development compiled version it does.

**Comment by alekseyg** [comment]
I'm having the same issue. In production and staging, all of the files being processed through browserify come out empty with browserify 14.1.0+. I tried 13.3.0-14.4.0 and it worked with 13.3.0 and 14.0.0, but everything above that failed.

Another thing is this problem only appears in the newer versions of browserify if browserify-incremental is disabled. Enabling it makes browserify-rails work with the latest browserify. You can do this by putting the following line in `production/staging.rb`

```ruby
  config.browserify_rails.use_browserifyinc = true
```

https://github.com/browserify-rails/browserify-rails/blob/d8005b081fec7481fe9718a0b98cf61cf3642455/lib/browserify-rails/railtie.rb#L25

**Comment by alekseyg** [comment]
The pull request for browserify 14.1.0 has this comment, which might have something to do with this issue: https://github.com/substack/node-browserify/pull/1673#issuecomment-273617535

**Comment by alekseyg** [comment]
As of v3.1.0, browserify-incremental no longer requires `fullPaths`, so enabling it on production and staging is safe now, at least according to my tests.

**Comment by cymen** [comment]
It might also be that the piping mode of browserify is broken. Last time it broke, I submitted a PR for the bug. substack suggested maybe doing a test for it too but there were more pressing issues and (this reminded me) it never got done. So first thing I'd do is pull down the new browserify and do some basic manual tests of piping a module in and making sure it emits the expected output.

**Comment by avit** [comment]
I ran into this as well. It looks like browserify is expecting to find .js files under app/assets. Running browserify manually shows an error:

```
Error: Cannot find module 'yes/it/exists' from '/app/app/assets/javascripts'
```

Since browserifyinc fixes this, I suspect that these are compiled into the cache and then found there. Otherwise it's looking for .js files, but there are only .coffee, .jsx, etc. files in the source location.

In addition to fixing the compilation issue, it should not fail silently on similar errors when running browserify and it gives exit status 1.

**Comment by cymen** [comment]
@avit That might be a browserify-rails configuration issue and not an issue with browserify itself? Or are you adding the additional paths to `config.browserify_rails.paths`? That is if they are outside of `app`. The default paths are added here:

https://github.com/browserify-rails/browserify-rails/blob/master/lib/browserify-rails/railtie.rb#L10-L12

**Comment by avit** [comment]
@cymen, no, these are not outside of app/assets. Just adding `use_browserifyinc = true` made it work so I'm only speculating about the reason based on that.

My file looked like this (js.coffee):

```
#= require one
#= require_tree two
#= require_self

window.GlobalThing =
  Builder: require('three')
```

The output included items _one_ and _two_, but silently ignored everything from `require_self`. If the file does not contain any `require` statements in the body, then the output is included. It seems to fail silently when `require` is used.

So, possibly something about the build order and those files not being compiled first as dependencies?

**Comment by cymen** [comment]
Hrm.. That is odd. My recommended approach is to put all of the code that uses CommonJS in one entry point that gets required via the sprockets require calls. If there are multiple entry points into CommonJS, it seems like it can cause problems.

But I never looked into it in greater depth so there might be other ways to do this that work well.

**Comment by cbeckr** [comment]
Same issue here and I second @avit. Seems this happens because browserify has no anchor point to resolve relative paths, since input is piped via stdin.

To reproduce, simply take the command logged by browserify-rails:

```
cat "/my/project/app/assets/javascripts/admin.js" | \
  /my/project/node_modules/.bin/browserify -t [ babelify --presets [ es2015 ] \
  --extensions .es6.js ] -o "/my/project/tmp/cache/browserify-rails/output20180806-8585-nezezb" -
Error: Cannot find module '../es6/widgets/some_widget.js' from '/my/project'
    at /my/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/my/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/my/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /my/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:158:21)
```

However, this would work:
```
/my/project/node_modules/.bin/browserify -t [ babelify --presets [ es2015 ] \
  --extensions .es6.js ] /my/project/app/assets/javascripts/admin.js
```

Setting ```config.browserify_rails.use_browserifyinc = true``` and clearing the sprockets cache (```bundle exec rake assets:clobber```) resolves the issue.
